# Generated by Django 3.2 on 2022-03-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('other', 'Other'), ('male', 'Male'), ('feminine', 'Feminine')], max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('client', 'Client'), ('film related', 'Film related')], max_length=120),
        ),
    ]
